// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class Bookmark
{
    public string BookmarkId { get; set; }

    public string UserId { get; set; }

    public string LineId { get; set; }

    public string StationId { get; set; }

    public bool? Status { get; set; }

    public virtual MetroLine Line { get; set; }

    public virtual MetroStation Station { get; set; }

    public virtual User User { get; set; }
}