// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class BusLine
{
    public string BusLineId { get; set; }

    public string BusLineName { get; set; }

    public string Route { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<BusSchedule> BusSchedules { get; set; } = new List<BusSchedule>();
}