// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class BusStationMetroStation
{
    public string Id { get; set; }

    public string BusStationId { get; set; }

    public string MetroStationId { get; set; }

    public double Distance { get; set; }

    public virtual BusStation BusStation { get; set; }

    public virtual MetroStation MetroStation { get; set; }
}