// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class BusSchedule
{
    public string ScheduleId { get; set; }

    public string BusLineId { get; set; }

    public string BusStationId { get; set; }

    public TimeOnly ArrivalTime { get; set; }

    public TimeOnly DepartureTime { get; set; }

    public string DayType { get; set; }

    public virtual BusLine BusLine { get; set; }

    public virtual BusStation BusStation { get; set; }
}