// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class BusStation
{
    public string BusStationId { get; set; }

    public string BusStationName { get; set; }

    public string Location { get; set; }

    public double? Latitude { get; set; }  // Chuyển sang kiểu double

    public double? Longitude { get; set; } // Chuyển sang kiểu double

    public bool? Status { get; set; }


    public virtual ICollection<BusSchedule> BusSchedules { get; set; } = new List<BusSchedule>();

    public virtual ICollection<BusStationMetroStation> BusStationMetroStations { get; set; } = new List<BusStationMetroStation>();
}