// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class History
{
    public string HistoryId { get; set; }

    public string UserId { get; set; }

    public DateTime? Timestamp { get; set; }

    public string Message { get; set; }

    public string RecommendId { get; set; }

    public virtual User User { get; set; }
}