// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class Log
{
    public string LogId { get; set; }

    public string UserId { get; set; }

    public string ScheduleId { get; set; }

    public string Location { get; set; }

    public DateTime? Date { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }
}