// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class MetroStation
{
    public string StationId { get; set; }

    public string StationName { get; set; }

    public string LineId { get; set; }

    public string Location { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<Bookmark> Bookmarks { get; set; } = new List<Bookmark>();

    public virtual ICollection<BusStationMetroStation> BusStationMetroStations { get; set; } = new List<BusStationMetroStation>();

    public virtual MetroLine Line { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}