// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MetroSystem.Data.Models;

public partial class Schedule
{
    public string ScheduleId { get; set; }

    public string LineId { get; set; }

    public string StationId { get; set; }

    public TimeOnly ArrivalTime { get; set; }

    public TimeOnly DepartureTime { get; set; }

    public virtual MetroLine Line { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual MetroStation Station { get; set; }
}